export enum Error {
  TokenExpired = 'TOKEN_EXPIRED',
  UserDisabled = 'USER_DISABLED',
  UserNotFound = 'USER_NOT_FOUND',
  InvalidRefreshToken = 'INVALID_REFRESH_TOKEN',
  InvalidGrantType = 'INVALID_GRANT_TYPE',
  MissingRefreshToken = 'MISSING_REFRESH_TOKEN',
  EmailExists = 'EMAIL_EXISTS',
  OperationNotAllowed = 'OPERATION_NOT_ALLOWED',
  TooManyAttempts = 'TOO_MANY_ATTEMPTS_TRY_LATER',
  EmailNotFound = 'EMAIL_NOT_FOUND',
  InvalidPassword = 'INVALID_PASSWORD',
  ExpiredOobCode = 'EXPIRED_OOB_CODE',
  InvalidOobCode = 'INVALID_OOB_CODE',
  InvalidIdToken = 'INVALID_ID_TOKEN',
  OldCredentials = 'CREDENTIAL_TOO_OLD_LOGIN_AGAIN',
  WeakPassword = 'WEAK_PASSWORD',
  InvalidEmail = 'INVALID_EMAIL',
  MissingPassword = 'MISSING_PASSWORD'
}

export const HumanReadableErrorMessage = {
  [Error.TokenExpired]: 'The user\'s credential is no longer valid. The user must sign in again.',
  [Error.UserDisabled]: 'The user account has been disabled by an administrator.',
  [Error.UserNotFound]: 'There is no user record corresponding to this identifier. The user may have been deleted.',
  [Error.InvalidRefreshToken]: 'An invalid refresh token was provided.',
  [Error.InvalidGrantType]: 'The grant type specified is invalid.',
  [Error.MissingRefreshToken]: 'No refresh token provided.',
  [Error.EmailExists]: 'The email address is already in use by another account.',
  [Error.OperationNotAllowed]: 'Password sign-in is disabled for this project.',
  [Error.TooManyAttempts]: 'We have blocked all requests from this device due to unusual activity. Try again later.',
  [Error.EmailNotFound]: 'There is no user record corresponding to this identifier. The user may have been deleted.',
  [Error.InvalidPassword]: 'The password is invalid or the user does not have a password.',
  [Error.ExpiredOobCode]: 'The action code has expired.',
  [Error.InvalidOobCode]: 'The action code is invalid. This can happen if the code is malformed, expired, or has already been used.',
  [Error.InvalidIdToken]: 'The user\'s credential is no longer valid. The user must sign in again.',
  [Error.OldCredentials]: 'The user\'s credential is no longer valid. The user must sign in again.',
  [Error.WeakPassword]: 'The password must be 6 characters long or more.',
  [Error.InvalidEmail]: 'The email address is invalid.',
  [Error.MissingPassword]: 'The password field is empty.',
};
